import * as fs from 'fs';
import * as path from 'path';

const chapterFiles = [
    "introduction-to-ethosism.md",
    "the-foundations-of-ethos.md",
    "what-it-means-to-be-an-ethosian.md",
    "a-secular-framework-for-life.md",
    "the-purpose-of-the-ethos-creed.md",
    "transcending-cultural-boundaries.md",
    "a-life-without-supernatural-beliefs.md",
    "the-power-of-naturalistic-motivation.md",
    "understanding-ethics-in-ethosism.md",
    "living-up-to-your-potential.md",
    "personal-growth-in-the-ethosian-way.md",
    "societal-growth-through-shared-values.md",
    "ethical-behavior-as-a-core-principle.md",
    "well-being-and-purpose-in-life.md",
    "critical-thinking-in-ethosism.md",
    "generational-responsibility-in-ethosism.md",
    "ancestral-duty-in-modern-times.md",
    "ethosism-vs-secular-humanism.md",
    "a-structured-approach-to-living.md",
    "the-universal-applicability-of-ethos.md",
    "the-impact-of-motivation-without-religion.md",
    "heaven-and-hell-the-secular-version.md",
    "ethosism-as-a-global-creed.md",
    "establishing-a-personal-creed.md",
    "the-importance-of-creed-continuity.md",
    "ethical-responsibilities-across-generations.md",
    "a-framework-for-productive-living.md",
    "why-we-need-structured-secularism.md",
    "generational-transmission-of-values.md",
    "living-with-intent-and-purpose.md",
    "the-role-of-ethics-in-daily-life.md",
    "naturalistic-principles-in-ethosism.md",
    "cultural-resonance-without-religion.md",
    "personal-success-in-ethosism.md",
    "failure-and-redemption-in-ethos.md",
    "adapting-to-change-keeping-core-values.md",
    "a-guide-to-ethical-decision-making.md",
    "human-potential-in-the-ethosian-view.md",
    "the-motivation-to-align-with-your-creed.md",
    "why-creed-matters-more-than-belief.md",
    "living-ethically-without-divinity.md",
    "generational-ethics-and-legacy.md",
    "ethosisms-approach-to-universal-truths.md",
    "the-psychology-of-secular-motivation.md",
    "a-new-kind-of-human-flourishing.md",
    "ethosism-as-a-beacon-for-progress.md",
    "cultural-inclusivity-in-ethosism.md",
    "defining-your-ethical-potential.md",
    "the-path-of-ethical-growth.md",
    "ethosisms-global-vision-for-humanity.md",
    "why-universalism-matters-in-ethics.md",
    "a-philosophy-for-all-humanity.md",
    "ethosisms-practical-guide-to-life.md",
    "ethosisms-creed-for-generational-strength.md",
    "adopting-ethosism-in-daily-practice.md",
    "building-a-framework-for-human-progress.md",
    "ethosism-and-the-pursuit-of-happiness.md",
    "natural-law-and-secular-morality.md",
    "a-rational-approach-to-meaning.md",
    "empowering-individuals-through-creed.md",
    "purpose-beyond-personal-desire.md",
    "why-generational-duty-is-important.md",
    "the-role-of-tradition-in-ethosism.md",
    "ethosisms-vision-for-the-future.md",
    "how-ethosism-guides-societal-change.md",
    "establishing-ethical-benchmarks.md",
    "practical-wisdom-in-secular-life.md",
    "ethosisms-role-in-shaping-culture.md",
    "a-roadmap-for-ethical-living.md",
    "ethosism-and-global-ethical-standards.md",
    "building-a-life-of-meaning.md",
    "the-core-values-of-ethosism.md",
    "the-generational-impact-of-values.md",
    "overcoming-modern-challenges-with-ethos.md",
    "ethosism-as-a-path-to-personal-fulfillment.md",
    "reinforcing-ethical-conduct.md",
    "ethosism-in-modern-society.md",
    "the-power-of-creed-over-belief.md",
    "ethosism-a-way-forward-for-humanity.md",
    "why-structure-matters-in-secular-life.md",
    "living-with-responsibility-and-integrity.md",
    "ethosisms-answer-to-human-questions.md",
    "universal-ethics-without-religion.md",
    "generational-alignment-and-progress.md",
    "ethosisms-ethical-roadmap-for-society.md",
    "a-secular-framework-for-well-being.md",
    "ethical-consistency-through-generations.md",
    "the-promise-of-personal-growth-in-ethosism.md",
    "living-with-the-legacy-of-your-ancestors.md",
    "ethosisms-role-in-ethical-evolution.md",
    "a-life-guided-by-rational-ethics.md",
    "a-philosophy-of-ethical-continuity.md",
    "achieving-ethical-balance-in-life.md",
    "ethosism-a-universal-creed-for-the-future.md",
    "fulfilling-human-potential-through-creed.md",
    "shaping-the-future-with-secular-values.md",
    "ethosisms-promise-for-generations.md",
    "the-lasting-legacy-of-ethosism.md",
    "concluding-thoughts-on-the-ethos-creed.md"
  ];

const createChapterFiles = () => {
  chapterFiles.forEach((fileName, index) => {
    const chapterNumber = (index + 1).toString().padStart(2, '0');
    const content = `# Chapter ${chapterNumber}: ${fileName.replace(/-/g, ' ').replace('.md', '').split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}\n\n## Introduction\n\n[Write your introduction here]\n\n## Main Content\n\n[Write your main content here]\n\n## Conclusion\n\n[Write your conclusion here]`;
    
    fs.writeFileSync(path.join(__dirname, `${chapterNumber}-${fileName}`), content);
    console.log(`Created ${chapterNumber}-${fileName}`);
  });
};

createChapterFiles();
