import { createRequestHandler } from "@react-router/architect";
// build output generated by `react-router build`
// @ts-expect-error - no types for build artifact
import * as build from "../build/server/index.js";

export const handler = createRequestHandler({
  build,
  mode: process.env.NODE_ENV,
});
