// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chapters": {
    params: {};
  };
  "/chapters/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chapters" | "/chapters/:slug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/chapters._index.tsx": {
    id: "routes/chapters._index";
    page: "/chapters";
  };
  "routes/chapters.$slug.tsx": {
    id: "routes/chapters.$slug";
    page: "/chapters/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/chapters._index": typeof import("./app/routes/chapters._index.tsx");
  "routes/chapters.$slug": typeof import("./app/routes/chapters.$slug.tsx");
};